# Generated by Django 5.0.7 on 2024-08-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Enter the title of the post",
                        max_length=100,
                        verbose_name="Title",
                    ),
                ),
                ("slug", models.CharField(max_length=150, verbose_name="Slug")),
                (
                    "body",
                    models.TextField(help_text="Enter the text", verbose_name="Body"),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Add a photo",
                        null=True,
                        upload_to="blog/photo",
                        verbose_name="Photo",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Publication date"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Published?"),
                ),
                ("views_count", models.IntegerField(default=0, verbose_name="Views")),
            ],
            options={
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
            },
        ),
    ]
