# Generated by Django 5.0.7 on 2024-08-30 12:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="created_at",
            field=models.DateField(
                blank=True,
                default=django.utils.timezone.now,
                null=True,
                verbose_name="Publication date",
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="views_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Views"),
        ),
    ]
