# Generated by Django 5.0.7 on 2024-09-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="current_version",
            field=models.BooleanField(
                default=True, verbose_name="Current version indicator"
            ),
        ),
    ]
