# Generated by Django 4.2.2 on 2024-09-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_product_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "category"],
                "permissions": [
                    ("can_cancel_publication", "Can cancel publication"),
                    ("can_edit_description", "Can edit description"),
                    ("can_change_category", "Cand change category"),
                ],
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(
                default=False, help_text="Publish", verbose_name="Published"
            ),
        ),
    ]
